const API_KEY="aad3fab1607b552befd9a2ac37e556af",BASE_URL="https://api.themoviedb.org/3",IMG_BASE_URL="https://image.tmdb.org/t/p/original";function fetchDetails(e,t){fetch(`${BASE_URL}/${t}/${e}?api_key=${API_KEY}&append_to_response=videos`).then(e=>e.json()).then(e=>displayDetails(e,t)).catch(e=>console.error("Error:",e))}function displayDetails(e,t){let a=document.querySelector(".backdrop-container"),i=document.getElementById("detail-poster"),r=document.getElementById("detail-title"),n=document.getElementById("detail-meta"),l=document.getElementById("detail-overview"),o=document.getElementById("watch-trailer-btn"),d=document.getElementById("watch-trailer-btn2"),c=document.getElementById("watch-trailer-btn3"),s=e.backdrop_path?IMG_BASE_URL+e.backdrop_path:"",m=e.poster_path?IMG_BASE_URL+e.poster_path:"",p=new Date(e.release_date||e.first_air_date).toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"});document.title=`${e.title||e.name} - Stream Now on JioStream`,a.style.backgroundImage=`url(${s})`,i.src=m,i.alt=e.title||e.name,r.textContent=e.title||e.name,n.innerHTML=`
        <span>${p}</span> | 
        <span>${"movie"===t?e.runtime+" min":e.episode_run_time[0]+" min/episode"}</span> | 
        <span>${e.genres.map(e=>e.name).join(", ")}</span>
    `,l.textContent=e.overview,o.style.display="block",o.onclick=()=>toggleTrailer(t,e.id),d.style.display="block",d.onclick=()=>toggleTrailer2(t,e.id),c.style.display="block",c.onclick=()=>toggleTrailer3(t,e.id)}function toggleTrailer(e,t){displayTrailer(t,"https://vidsrc.dev/embed/"+("movie"===e?`movie/${t}`:`tv/${t}/1/1`),"trailer-container")}function toggleTrailer2(e,t){displayTrailer(t,"https://hnembed.cc/embed/"+("movie"===e?`movie/${t}`:`tv/${t}`),"trailer-container2")}function toggleTrailer3(e,t){displayTrailer(t,"https://multiembed.mov/?video_id="+t+"&tmdb=1"+("tv"===e?"&s=1&e=1":""),"trailer-container3")}function displayTrailer(e,t,a){["trailer-container","trailer-container2","trailer-container3"].forEach(e=>{let t=document.getElementById(e);t.classList.remove("active"),t.innerHTML=""});let i=document.getElementById(a);i.classList.add("active"),i.innerHTML=`<iframe src="${t}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`}function fetchRelatedContent(e,t){fetch(`${BASE_URL}/${t}/${e}/recommendations?api_key=${API_KEY}`).then(e=>e.json()).then(e=>displayRelatedContent(e.results.slice(0,10),t)).catch(e=>console.error("Error:",e))}function displayRelatedContent(e,t){let a=document.getElementById("related-grid");a.innerHTML="",e.forEach(e=>{let i=document.createElement("div");i.className="movie-card";let r=e.poster_path?`${IMG_BASE_URL}/${e.poster_path}`:"",n=new Date(e.release_date||e.first_air_date).toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"}),l=Math.round(10*e.vote_average);i.innerHTML=`
            <img class="movie-poster" src="${r}" alt="${e.title||e.name}">
            <div class="movie-info">
                <h2 class="movie-title">${e.title||e.name}</h2>
                <p class="movie-release-date">${n}</p>
                <div class="movie-overview">${e.overview}</div>
            </div>
            <div class="movie-rating">${l}%</div>
        `,i.addEventListener("click",()=>{window.location.href=`detail.html?id=${e.id}&type=${t}`}),a.appendChild(i)})}async function fetchDataWithExpiry(e,t=60){let a=`tmdb_${e}`,i=JSON.parse(localStorage.getItem(a));if(i&&Date.now()-i.timestamp<6e4*t)return console.log("Loading data from cache with expiry check"),i.data;try{let r=await fetch(`https://api.themoviedb.org/3/${e}`),n=await r.json();return localStorage.setItem(a,JSON.stringify({data:n,timestamp:Date.now()})),console.log("Data cached in localStorage with expiry"),n}catch(l){return console.error("Error fetching data:",l),null}}document.addEventListener("DOMContentLoaded",()=>{let e=new URLSearchParams(window.location.search),t=e.get("id"),a=e.get("type");t&&a&&(fetchDetails(t,a),fetchRelatedContent(t,a))});