const API_KEY="aad3fab1607b552befd9a2ac37e556af",BASE_URL="https://api.themoviedb.org/3",IMG_BASE_URL="https://image.tmdb.org/t/p/original";function fetchDetails(e,t){fetch(`${BASE_URL}/${t}/${e}?api_key=${API_KEY}&append_to_response=videos`).then(e=>e.json()).then(e=>displayDetails(e,t)).catch(e=>console.error("Error:",e))}function displayDetails(e,t){let a=document.querySelector(".backdrop-container"),i=document.getElementById("detail-poster"),n=document.getElementById("detail-title"),r=document.getElementById("detail-meta"),l=document.getElementById("detail-overview"),o=document.getElementById("watch-trailer-btn"),d=document.getElementById("watch-trailer-btn2"),c=document.getElementById("watch-trailer-btn3"),s=e.backdrop_path?IMG_BASE_URL+e.backdrop_path:"",m=e.poster_path?IMG_BASE_URL+e.poster_path:"",p=new Date(e.release_date||e.first_air_date).toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"});a.style.backgroundImage=`url(${s})`,i.src=m,i.alt=e.title||e.name,n.textContent=e.title||e.name,r.innerHTML=`
        <span>${p}</span> | 
        <span>${"movie"===t?e.runtime+" min":e.episode_run_time[0]+" min/episode"}</span> | 
        <span>${e.genres.map(e=>e.name).join(", ")}</span>
    `,l.textContent=e.overview,o.style.display="block",o.onclick=()=>toggleTrailer(t,e.id),d.style.display="block",d.onclick=()=>toggleTrailer2(t,e.id),c.style.display="block",c.onclick=()=>toggleTrailer3(t,e.id)}function toggleTrailer(e,t){let a=document.getElementById("trailer-container"),i=document.getElementById("trailer-container2"),n=document.getElementById("trailer-container3");i.classList.remove("active"),i.innerHTML="",n.classList.remove("active"),n.innerHTML="";let r="movie"===e?`https://vidsrc.dev/embed/movie/${t}`:`https://vidsrc.dev/embed/tv/${t}/1/1`;a.classList.add("active"),a.innerHTML=`<iframe src="${r}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`}function toggleTrailer2(e,t){let a=document.getElementById("trailer-container"),i=document.getElementById("trailer-container2"),n=document.getElementById("trailer-container3");a.classList.remove("active"),a.innerHTML="",n.classList.remove("active"),n.innerHTML="";let r="movie"===e?`https://hnembed.cc/embed/movie/${t}`:`https://hnembed.cc/embed/tv/${t}`;i.classList.add("active"),i.innerHTML=`<iframe src="${r}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`}function toggleTrailer3(e,t){let a=document.getElementById("trailer-container"),i=document.getElementById("trailer-container2"),n=document.getElementById("trailer-container3");a.classList.remove("active"),a.innerHTML="",i.classList.remove("active"),i.innerHTML="";let r="movie"===e?`https://multiembed.mov/?video_id=${t}&tmdb=1`:`https://multiembed.mov/?video_id=${t}&tmdb=1&s=1&e=1`;n.classList.add("active"),n.innerHTML=`<iframe src="${r}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`}function fetchRelatedContent(e,t){fetch(`${BASE_URL}/${t}/${e}/recommendations?api_key=${API_KEY}`).then(e=>e.json()).then(e=>displayRelatedContent(e.results.slice(0,10),t)).catch(e=>console.error("Error:",e))}function displayRelatedContent(e,t){let a=document.getElementById("related-grid");a.innerHTML="",e.forEach(e=>{let i=document.createElement("div");i.className="movie-card";let n=e.poster_path?`${IMG_BASE_URL}/${e.poster_path}`:"",r=new Date(e.release_date||e.first_air_date).toLocaleDateString("en-US",{year:"numeric",month:"long",day:"numeric"}),l=Math.round(10*e.vote_average);i.innerHTML=`
            <img class="movie-poster" src="${n}" alt="${e.title||e.name}">
            <div class="movie-info">
                <h2 class="movie-title">${e.title||e.name}</h2>
                <p class="movie-release-date">${r}</p>
                <div class="movie-overview">${e.overview}</div>
            </div>
            <div class="movie-rating">${l}%</div>
        `,i.addEventListener("click",()=>{window.location.href=`detail.html?id=${e.id}&type=${t}`}),a.appendChild(i)})}async function fetchDataWithExpiry(e,t=60){let a=`tmdb_${e}`,i=JSON.parse(localStorage.getItem(a));if(i&&Date.now()-i.timestamp<6e4*t)return console.log("Loading data from cache with expiry check"),i.data;try{let n=await fetch(`https://api.themoviedb.org/3/${e}`),r=await n.json();return localStorage.setItem(a,JSON.stringify({data:r,timestamp:Date.now()})),console.log("Data cached in localStorage with expiry"),r}catch(l){return console.error("Error fetching data:",l),null}}document.addEventListener("DOMContentLoaded",()=>{let e=new URLSearchParams(window.location.search),t=e.get("id"),a=e.get("type");e.get("season"),e.get("episode"),t&&a&&(fetchDetails(t,a),fetchRelatedContent(t,a))}),setInterval(()=>{(window.outerWidth-window.innerWidth>160||window.outerHeight-window.innerHeight>160)&&(alert("Developer tools are not allowed!"),window.location.href="https://jiostream.netlify.app")},1e3),setInterval(()=>{},5e3),document.addEventListener("contextmenu",e=>e.preventDefault()),document.onkeydown=function(e){if(123===e.keyCode||e.ctrlKey&&e.shiftKey&&(73===e.keyCode||67===e.keyCode)||e.ctrlKey&&85===e.keyCode)return alert("Shortcut disabled!"),!1},function e(){let t=!1,a=new Image;Object.defineProperty(a,"id",{get:function(){t=!0,setTimeout(()=>{t&&(window.location.href="https://jiostream.netlify.app")},500)}}),console.log("%c ",a)}(),fetchDataWithExpiry("movie/popular").then(e=>{e&&console.log("Data loaded:",e)});